// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using community_dotnet.Models;

namespace communitydotnet.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20181019223248_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("community_dotnet.Models.MessagePoco", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FromUserUsername");

                    b.Property<bool>("IsSeen");

                    b.Property<string>("TextMessage");

                    b.Property<string>("Timestamp")
                        .IsRequired();

                    b.Property<string>("ToUserUsername");

                    b.HasKey("MessageId");

                    b.HasIndex("FromUserUsername");

                    b.HasIndex("ToUserUsername");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("community_dotnet.Models.UserPoco", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("LatestLogin");

                    b.Property<int>("NumberOfLoginsInMonth");

                    b.Property<int>("NumberOfMessageSent");

                    b.Property<int>("NumberOfUnreadMessages");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("community_dotnet.Models.MessagePoco", b =>
                {
                    b.HasOne("community_dotnet.Models.UserPoco", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserUsername");

                    b.HasOne("community_dotnet.Models.UserPoco", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserUsername");
                });
#pragma warning restore 612, 618
        }
    }
}
